version: '2'

services:
  coremvc:
    image: coremvc:dev
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - ./coreMVC:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
  db:
    image: db:dev
    ports:
     - "5432:5432"
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
volumes:
    postgres_data:
        external: true