version: '2'

services:
  coremvc:
    image: coremvc
    build:
      context: ./CoreMVC
      dockerfile: Dockerfile
    links:
      - db:db
    depends_on:
      - db

  db:
    image: db
    build:
       context: ./db
       dockerfile: Dockerfile